// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticeProject1.Data;

#nullable disable

namespace PracticeProject1.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240211074128_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PracticeProject1.Models.Product", b =>
                {
                    b.Property<int>("LaptopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaptopId"), 1L, 1);

                    b.Property<string>("LaptopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaptopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LaptopRate")
                        .HasColumnType("float");

                    b.HasKey("LaptopId");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            LaptopId = 201,
                            LaptopDescription = "12th Generation Intel® Core™ i3 processor\r\nFreeDOS 3.0\r\n(15.6) 39.62 cm diagonal, HD anti-glare display with Intel® Iris® Xᵉ Graphics\r\n8 GB DDR4-3200 MHz RAM (1 x 8 GB)",
                            LaptopName = "HP",
                            LaptopRate = 48000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
